---
- name: Instalar aplicativos no cliente1
  hosts: cliente1
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Atualizar a lista de pacotes
      apt:
        update_cache: yes

    - name: Instalar vim
      apt:
        name: vim
        state: present

    - name: Instalar telnet
      apt:
        name: telnet
        state: present

    - name: Instalar tcpdump
      apt:
        name: tcpdump
        state: present

    - name: Instalar nfs-common
      apt:
        name: nfs-common
        state: present

    - name: Instalar wget
      apt:
        name: wget
        state: present

    - name: Instalar chrony
      apt:
        name: chrony
        state: present

    - name: Instalar net-tools
      apt:
        name: net-tools
        state: present

    - name: Instalar bzip2
      apt:
        name: bzip2
        state: present

    - name: Instalar zip
      apt:
        name: zip
        state: present

    - name: Instalar git
      apt:
        name: git
        state: present

    - name: Instalar bridge-utils
      apt:
        name: bridge-utils
        state: present

    - name: Instalar traceroute
      apt:
        name: traceroute
        state: present

    - name: Instalar whois
      apt:
        name: whois
        state: present

    - name: Instalar htop
      apt:
        name: htop
        state: present

    - name: Instalar mtr
      apt:
        name: mtr
        state: present

    - name: Instalar iftop
      apt:
        name: iftop
        state: present

    - name: Instalar rsyslog
      apt:
        name: rsyslog
        state: present

    - name: Instalar iotop
      apt:
        name: iotop
        state: present

    - name: Instalar iputils-ping
      apt:
        name: iputils-ping
        state: present

    - name: Instalar cloud-utils
      apt:
        name: cloud-utils
        state: present
